LibraryCarpentry/lc-spreadsheets

- _episodes/06-data-formats-caveats.md
Fix for https://github.com/LibraryCarpentry/lc-spreadsheets/issues/17
> Fix links to species data and previous lesson

- _episodes/00-intro.md
Rendering was obfuscated by `---` under unordered list. adding a space corrects.
> fixing horizontal line under - Plotting on ep.1

- _episodes/01-format-data.md
formatting exercise on 01-format-data
> formatting excise as challenge

- _episodes/03-dates-as-data.md
> Fixed broken links unde  "Preferred date format" notes.

- _episodes/02-common-mistakes.md
Fixing link identified in #27  in https://github.com/LibraryCarpentry/lc-spreadsheets/blob/gh-pages/_episodes/02-common-mistakes.md
> Correcting link "Date formatting" in Formatting Problems episode 

- _episodes/02-common-mistakes.md
PR from #42 had two changes, one was not a good fix (it actually would have broken a link).
So I created this pull request with just the one change - addition to LibreOffice link.
> added Link how to freeze in LibreOffice

- _episodes/01-format-data.md
Making sure my new cloning works.
> new author

- setup.md
As per issue listed https://github.com/LibraryCarpentry/lc-spreadsheets/issues/2 
Omitted references to colours and versions, can add something regarding this in the instructor notes.
Please delete this line and the text below before submitting your contribution.
---
Thanks for contributing! If this contribution is for instructor training, please send an email to checkout@carpentries.org with a link to this contribution so we can record your progress. You’ve completed your contribution step for instructor checkout just by submitting this contribution.  
Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and …
> LibreOffice Version removed

- _episodes/00-intro.md
Suggested objective for this lesson
Please delete this line and the text below before submitting your contribution.
---
Thanks for contributing! If this contribution is for instructor training, please send an email to checkout@carpentries.org with a link to this contribution so we can record your progress. You’ve completed your contribution step for instructor checkout just by submitting this contribution.  
Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution …
> objective added

- _episodes/00-intro.md
line 114 is a description and question not 2 questions.
Please delete this line and the text below before submitting your contribution.
---
Thanks for contributing! If this contribution is for instructor training, please send an email to checkout@carpentries.org with a link to this contribution so we can record your progress. You’ve completed your contribution step for instructor checkout just by submitting this contribution.  
Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your …
> question format

- _episodes/03-dates-as-data.md
changes to line 152 and 157 to resolve anachronism issue in text of "dates as data" example problem in excel. https://github.com/LibraryCarpentry/lc-spreadsheets/issues/5
> text_anachronism_fix

- _episodes/03-dates-as-data.md
> Removed "Challenge" callout

- _config.yml
Added lifecycle metadata to lesson in _config.yml and set to "stable".
> adding stable status to config

- README.md
adding zenodo badge and citation to README.
> adding zenodo badge and citation

- _episodes/01-format-data.md
Replaced "dumb" with "unintelligent".
<details>
<summary><strong>Instructions</strong></summary>
Thanks for contributing! :heart:
If this contribution is for instructor training, please email the link to this contribution to
checkout@carpentries.org so we can record your progress. You've completed your contribution
step for instructor checkout by submitting this contribution!
Keep in mind that **lesson maintainers are volunteers** and it may take them some time to
respond to your contribution. Although not all contributions can be incorporated into the lesson
materials, we appreciate your time and effort to improve the curriculum. If you have any questions
about the lesson maintenance process or would like to volunteer your time as a contribution
reviewer, please contact The Carpentries …
> Fixed ableist language

- _episodes/03-dates-as-data.md
- _episodes/04-quality-control.md
> Date & QA Episode Fixes

- _episodes/05-exporting-data.md
<details>
<summary><strong>Instructions</strong></summary>
Thanks for contributing! :heart:
If this contribution is for instructor training, please email the link to this contribution to
checkout@carpentries.org so we can record your progress. You've completed your contribution
step for instructor checkout by submitting this contribution!
Keep in mind that **lesson maintainers are volunteers** and it may take them some time to
respond to your contribution. Although not all contributions can be incorporated into the lesson
materials, we appreciate your time and effort to improve the curriculum. If you have any questions
about the lesson maintenance process or would like to volunteer your time as a contribution
reviewer, please contact The Carpentries Team at team@carpentries.org.
You may …
> Fixed a spelling error

- setup.md
> Replace Mac OS X with macOS (the name since 2016)

- _episodes/02-common-mistakes.md
Alt-text submission made during Core Team Accessibility session. Ready for review.
> adding alt text to spreadsheet image

- _episodes/00-intro.md
- _episodes/01-format-data.md
- _episodes/02-common-mistakes.md
Closes #109. 
- Adds Google Sheets as an example program.
- Updates names of other programs.
- Fixes typo.
- Adds documentation for how to freeze column headers in Google Sheets.
> closes #109 adds Google Sheets and fixes typo

- _episodes/03-dates-as-data.md
Updated language from open in finder (Mac only) to also include explorer (Windows)
<details>
<summary><strong>Instructions</strong></summary>
Thanks for contributing! :heart:
If this contribution is for instructor training, please email the link to this contribution to
checkout@carpentries.org so we can record your progress. You've completed your contribution
step for instructor checkout by submitting this contribution!
Keep in mind that **lesson maintainers are volunteers** and it may take them some time to
respond to your contribution. Although not all contributions can be incorporated into the lesson
materials, we appreciate your time and effort to improve the curriculum. If you have any questions
about the lesson maintenance process or would like to volunteer your time as a …
> Improve cross-platform clarity

- _episodes/03-dates-as-data.md
This PR addresses issue #127 by fixing a typo and also clarifies and explains the example illustrated in the image.
> Issue 127 revision

- _episodes/03-dates-as-data.md
The changes proposed in this branch address issues gathered in issue #130 , which have been accumulating for a while. Since there were a few I also ended up making a general revision of a lot of the text in the episode, as well as the ordering of the sections. I'd appreciate it if another maintainer could take a look before this is merged.
> Refresh date episode and address outstanding issues

- _episodes/02-common-mistakes.md
This branch is intended to address the issues in issue #124 . 
Changes: 
* update null value table to text, to improve accessibility of the information
* correct citation to the source article for the null value suggestions
* update and revise the problem/solution text for the null value example to better match the versions in DataCarpentry version of the lesson.
> Fix issue 124 bad null vals table

- episodes/00-intro.md
- episodes/01-format-data.md
- episodes/02-common-mistakes.md
- episodes/03-dates-as-data.md
- episodes/04-quality-control.md
- episodes/05-exporting-data.md
- episodes/06-data-formats-caveats.md
- instructors/instructor-notes.md
Moved to the top of individual lessons.
Wasn't sure what to do with the concluding narrative notes, so I've left those alone.
> Move instructor notes narrative guidance to individual lessons

- CONTRIBUTING.md
Please delete this line and the text below before submitting your contribution.
---
Thanks for contributing! If this contribution is for instructor training, please send an email to checkout@carpentries.org with a link to this contribution so we can record your progress. You’ve completed your contribution step for instructor checkout just by submitting this contribution.
Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, please contact The …
> add repo link for contributing to complete PR #140

- README.md
- episodes/02-common-mistakes.md
- episodes/04-quality-control.md
- episodes/05-exporting-data.md
- index.md
- learners/setup.md
This PR addresses multiple formatting issues and revisions in response to the changeover to the Workbench styles and templates. It specifically addresses issue #137 , and other revisions and copyedits in response to the template changes.
> Post transition formatting corrections

- episodes/00-intro.md
adding excel bible to [00-intro.html](https://datacarpentry.org/spreadsheet-ecology-lesson/00-intro.html), closes #150
> adding more recent excel reference book

- learners/reference.md
> adding excel resources to reference page
